version: '3.8'
networks:
  coolify:
    external: true
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SOURCE_COMMIT=${SOURCE_COMMIT:-unknown}
    deploy:
      replicas: 3
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deployment-testing-service.rule=Host(`test.intellsys.in`)"
      - "traefik.http.services.deployment-testing-service.loadbalancer.server.port=3000"
      - "coolify.managed=true"
      - "coolify.applicationId=19"
      - "coolify.type=application"
